services:
    apache:
        image: httpd:latest
        ports:
            - "8000:80"
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs 
        container_name: dam_apache
    db:
        image: mariadb:10.6.4-focal
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
          - db_data:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=castelao
          - MYSQL_DATABASE=wordpress
          - MYSQL_USER=juan
          - MYSQL_PASSWORD=castelao
        container_name: dam_mdb 
        expose:
          - 3306
          - 33060
    wordpress:
        image: wordpress:latest
        volumes:
          - wp_data:/var/www/html
        ports:
          - "800:80"
        environment:
          - WORDPRESS_DB_HOST=db
          - WORDPRESS_DB_USER=juan
          - WORDPRESS_DB_PASSWORD=castelao
          - WORDPRESS_DB_NAME=wordpress
        container_name: dam_worpress
volumes:
    db_data:
    wp_data:                    
